version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run: apk add --update curl
      - run:
          name: Install dependencies
          command: |
            if curl -s --head "https://google3333.com" 
            then
              return 0
            else
              return 1
            fi

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure






