# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A command to print the id of the pipeline that we are working on now"
    parameters:
      to:
        type: string
        default: "hello motha fucker"
    steps:
      - run: echo << parameters.to >>
jobs:
  print_pipeline_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - sayhello:
          to: "$CIRCLE_WORKFLOW_ID"


workflows:
  test-env-vars:
    jobs:
      - print_pipeline_job





