version: 2.1
commands:
  destroy_environment:
    description: "Destroying the stack"
    steps:
      - run: 
          command: |
            aws cloudformation delete-stack --stackname myteststack

jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: building the stack
          command: |
            aws cloudformation deploy --stack-name myteststack --template-body template.yml
      - run : return 1
      - destroy_environment
          when : on_fail


workflows:
  my_workflow:
    jobs:
      - configure_infrastructure






